# NumPy Exercises

Reference for some of these exercises is [here](https://www.w3resource.com/python-exercises/).

## Exercise 1

Write a NumPy program to create a random array with 100 real-valued elements between 1 & 5 and compute the following for this array rounded to 2 decimal places:
- average (that is, the sample mean)
- population variance and population standard deviation (default option in NumPy)
- sample variance and sample standard deviation

**Hint:** For sample variance and sample standard deviation, use the `ddof=1` parameter value.

**Explanations**

Population variance

$$\text{Population variance} = \frac{\sum_{i=1}^{N}(X_i - \bar{X})^{2}}{N}$$

Sample variance

$$\text{Sample variance} = \frac{\sum_{i=1}^{N}(X_i - \bar{X})^{2}}{N-1}$$

In [1]:
import numpy as np
np.random.seed(999)
a = 1+ 4*np.random.rand(100)


## Execise 2

Write a NumPy program to get the values and indices of the elements that are bigger than 10 in a given array. 

In [26]:
import numpy as np

a = np.array([[1, 2, 45, 56, 3, 7, 67]])
result_dict = {}

# Flatten the array to iterate over each element
flat_a = a.flatten()

for index, value in enumerate(flat_a):
    if value > 10:
        # Add the element and its index to the dictionary
        result_dict[value] = index

print(result_dict)


{45: 2, 56: 3, 67: 6}


## Exercise 3

Write a NumPy program to find the set difference of two arrays. The set difference will return the sorted, unique values in the first array `array1` that are not in the second one `array2`. **Hint:** This is a one-liner.

In [ ]:
array1 = np.array([1,4,5,6,7,8,10,12] ) #1 + np.random.rand(20).round(2)
array2 = np.array([1,3,5,10,11])#1 + np.random.rand(20).round(2)


## Exercise 4

Write a NumPy program to calculate element-wise round, floor, ceiling, and truncated form of an input array.

In [21]:
import numpy as np

# Define a sample array with floating point numbers
arr = np.array([1.23, 2.65, -3.45, 4.56, -5.75])

# Calculate the rounded values
rounded_arr = np.round(arr)

# Calculate the floor values
floor_arr = np.floor(arr)

# Calculate the ceiling values
ceiling_arr = np.ceil(arr)

# Calculate the truncated values
truncated_arr = np.trunc(arr)

print("Original array:")
print(arr)
print("\nRounded:")
print(rounded_arr)
print("\nFloor:")
print(floor_arr)
print("\nCeiling:")
print(ceiling_arr)
print("\nTruncated:")
print(truncated_arr)


Original array:
[ 1.23  2.65 -3.45  4.56 -5.75]

Rounded:
[ 1.  3. -3.  5. -6.]

Floor:
[ 1.  2. -4.  4. -6.]

Ceiling:
[ 2.  3. -3.  5. -5.]

Truncated:
[ 1.  2. -3.  4. -5.]
